### ISSUE TITLE
Face-Recognition-Based-Attendance-System-master facing issue when click at train image

### ISSUE THREAD

**Issue by malikatiq786** [ashish8858/Face-Recognition-Based-Attendance-System#2]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Malik Atiq\Desktop\Face-Recognition-Based-Attendance-System-master\Face-Recognition-Based-Attendance-System-master\train.py", line 161, in TrainImages
    recognizer = cv2.face_LBPHFaceRecognizer.create()#recognizer = cv2.face.LBPHFaceRecognizer_create()#$cv2.createLBPHFaceRecognizer()
AttributeError: module 'cv2.cv2' has no attribute 'face_LBPHFaceRecognizer'

**Comment by mayurkadampro** [comment]
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "C:\Python37\lib\tkinter__init__.py", line 1705, in **call**
> return self.func(*args)
> File "C:\Users\Malik Atiq\Desktop\Face-Recognition-Based-Attendance-System-master\Face-Recognition-Based-Attendance-System-master\train.py", line 161, in TrainImages
> recognizer = cv2.face_LBPHFaceRecognizer.create()#recognizer = cv2.face.LBPHFaceRecognizer_create()#$cv2.createLBPHFaceRecognizer()
> AttributeError: module 'cv2.cv2' has no attribute 'face_LBPHFaceRecognizer'

well you just need to replace recognizer = cv2.face_LBPHFaceRecognizer.create() to recognizer = cv2.face.LBPHFaceRecognizer_create()

**Comment by mayurkadampro** [comment]
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "C:\Python37\lib\tkinter__init__.py", line 1705, in **call**
> return self.func(*args)
> File "C:\Users\Malik Atiq\Desktop\Face-Recognition-Based-Attendance-System-master\Face-Recognition-Based-Attendance-System-master\train.py", line 161, in TrainImages
> recognizer = cv2.face_LBPHFaceRecognizer.create()#recognizer = cv2.face.LBPHFaceRecognizer_create()#$cv2.createLBPHFaceRecognizer()
> AttributeError: module 'cv2.cv2' has no attribute 'face_LBPHFaceRecognizer'

I made changes in that train.py file you can check out from pull request else check out forked repo in my profile and now it's working fine.
