### ISSUE TITLE
yml file is not getting created

### ISSUE THREAD

**Issue by rachiitgupta** [ashish8858/Face-Recognition-Based-Attendance-System#24]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "train.py", line 194, in TrackImages
    recognizer.read("Trainner.yml")
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'cv::face::FaceRecognizer::read'

I can understand that yml file is not getting created as there is not TrainingImageLabel folder

**Comment by sayendutta** [comment]
same error for me too

**Comment by uday360** [comment]
change this (cam = cv2.VideoCapture(0) ) to cam = cv2.VideoCapture(0,cv2.CAP_DSHOW) in train.py

**Comment by abdullah0307** [comment]
it didnot work

**Comment by Sangamg145** [comment]
create   TrainingImageLabel   folder and make a trainner.yml text file on it

**Comment by srimanth12** [comment]
am unable to load yml file
