### ISSUE TITLE
df=pd.read_csv("StudentDetails\StudentDetails.csv") has SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by the-vis-sharma** [ashish8858/Face-Recognition-Based-Attendance-System#3]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File ".\train.py", line 197, in TrackImages
    df=pd.read_csv("StudentDetails\StudentDetails.csv")
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 422, in _read
    compression = _infer_compression(filepath_or_buffer, compression)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\common.py", line 277, in _infer_compression
    filepath_or_buffer = _stringify_path(filepath_or_buffer)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\common.py", line 150, in _stringify_path
    from py.path import local as LocalPath
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\py.py", line 1
    Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
             ^
SyntaxError: invalid syntax

**Comment by mayurkadampro** [comment]
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\tkinter__init__.py", line 1699, in **call**
> return self.func(*args)
> File ".\train.py", line 197, in TrackImages
> df=pd.read_csv("StudentDetails\StudentDetails.csv")
> File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
> return _read(filepath_or_buffer, kwds)
> File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 422, in _read
> compression = _infer_compression(filepath_or_buffer, compression)
> File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\common.py", line 277, in _infer_compression
> filepath_or_buffer = _stringify_path(filepath_or_buffer)
> File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\common.py", line 150, in _stringify_path
> from py.path import local as LocalPath
> File "C:\Users\user\AppData\Local\Programs\Python\Python36\py.py", line 1
> Python 3.6.3 (v3.6.3:2c5fed8, Oct 3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
> ^
> SyntaxError: invalid syntax

I made changes in that train.py file you can check out from pull request else check out forked repo in my profile and now it's working fine.
