### ISSUE TITLE
Getting error in line 

### ISSUE THREAD

**Issue by ghost** [ashish8858/Face-Recognition-Based-Attendance-System#4]

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "C:\Users\Rishi147\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "D:\mini project\New folder\test.py", line 185, in TrackImages
    aa=df.loc[df['Id'] == Id]['Name'].values
  File "C:\Users\Rishi147\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\Rishi147\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\Rishi147\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\Rishi147\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\Users\Rishi147\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Id'

**Comment by AbhiRudra** [comment]
same error for me too.. have you got any solution?

**Comment by ghost** [comment]
Add column names as Id and Name in StudentDetails\StudentDetails.csv file.

**Comment by AbhiRudra** [comment]
How should i do that will you help me?

**Comment by ghost** [comment]
In StudentDetails folder u will find a csv file after taking images of user. Just add two columns at the top and name 1st column as  Id and other column as Name and save it. Now everything should work fine

**Comment by AbhiRudra** [comment]
Thank you so much.. worked for me..!
Great help!

**Comment by Ahmadjan9687** [comment]
thank you so much @Rishikusumba  you made me happy to resolve this issue.

**Comment by rajivpatnaikiot** [comment]
Thanks a Lot @Rishikusumba. Its working.

**Comment by Ahmadjan9687** [comment]
what should i do first?
Us just to subscribe u..
