### ISSUE TITLE
Tkinter callback error

### ISSUE THREAD

**Issue by AmanRelan** [ashish8858/Face-Recognition-Based-Attendance-System#5]
i Get an error when i click on track images and then it gets stuck and does not work .. can you please help me resolve this issue?

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python37-32\lib\site-packages\pandas\core\indexes\base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37-32\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Users\relan\Desktop\Aman\New folder\Face-Recognition-Based-Attendance-System-master\train.py", line 195, in TrackImages
    aa=df.loc[df['Id'] == Id]['Name'].values
  File "C:\Python37-32\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Python37-32\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Python37-32\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Python37-32\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\Python37-32\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Id'
```

**Comment by mayurkadampro** [comment]
> i Get an error when i click on track images and then it gets stuck and does not work .. can you please help me resolve this issue?
> 
> ```
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "C:\Python37-32\lib\site-packages\pandas\core\indexes\base.py", line 3078, in get_loc
>     return self._engine.get_loc(key)
>   File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'Id'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python37-32\lib\tkinter\__init__.py", line 1702, in __call__
>     return self.func(*args)
>   File "C:\Users\relan\Desktop\Aman\New folder\Face-Recognition-Based-Attendance-System-master\train.py", line 195, in TrackImages
>     aa=df.loc[df['Id'] == Id]['Name'].values
>   File "C:\Python37-32\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
>     return self._getitem_column(key)
>   File "C:\Python37-32\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
>     return self._get_item_cache(key)
>   File "C:\Python37-32\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
>     values = self._data.get(item)
>   File "C:\Python37-32\lib\site-packages\pandas\core\internals.py", line 4115, in get
>     loc = self.items.get_loc(item)
>   File "C:\Python37-32\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
>     return self._engine.get_loc(self._maybe_cast_indexer(key))
>   File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'Id'
> ```

I made changes in that train.py file you can check out from pull request else check out forked repo in my profile and now it's working fine.

**Comment by kraverkar17** [comment]
> > i Get an error when i click on track images and then it gets stuck and does not work .. can you please help me resolve this issue?
> > ```
> > Exception in Tkinter callback
> > Traceback (most recent call last):
> >   File "C:\Python37-32\lib\site-packages\pandas\core\indexes\base.py", line 3078, in get_loc
> >     return self._engine.get_loc(key)
> >   File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
> >   File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
> >   File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
> >   File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
> > KeyError: 'Id'
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "C:\Python37-32\lib\tkinter\__init__.py", line 1702, in __call__
> >     return self.func(*args)
> >   File "C:\Users\relan\Desktop\Aman\New folder\Face-Recognition-Based-Attendance-System-master\train.py", line 195, in TrackImages
> >     aa=df.loc[df['Id'] == Id]['Name'].values
> >   File "C:\Python37-32\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
> >     return self._getitem_column(key)
> >   File "C:\Python37-32\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
> >     return self._get_item_cache(key)
> >   File "C:\Python37-32\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
> >     values = self._data.get(item)
> >   File "C:\Python37-32\lib\site-packages\pandas\core\internals.py", line 4115, in get
> >     loc = self.items.get_loc(item)
> >   File "C:\Python37-32\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
> >     return self._engine.get_loc(self._maybe_cast_indexer(key))
> >   File "pandas\_libs\index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
> >   File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
> >   File "pandas\_libs\hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
> >   File "pandas\_libs\hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
> > KeyError: 'Id'
> > ```
> 
> I made changes in that train.py file you can check out from pull request else check out forked repo in my profile and now it's working fine.

checked out the updated train.py but again and again I'm getting the same error............  in pycharm and in spyder when running the same code not showing any error but the at the time of track images the window gets stuck .....neither gets quit nor it tracks....... just shows unknown again and again......

trying to resolve this problem  from last few days...but.....nothing happened

plzz help

**Comment by SindhujaVakkalagadda** [comment]
I got the same error. If anyone has solution, please help me out

**Comment by asstian111** [comment]
我也遇到了相同的错误，请帮帮我
