### ISSUE TITLE
Exception in TKinter callback

### ISSUE THREAD

**Issue by divyasri456** [ashish8858/Face-Recognition-Based-Attendance-System#6]
Been stuck at this point. please help me out from this

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\divya\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "train.py", line 161, in TrainImages
    recognizer = cv2.face_LBPHFaceRecognizer.create()#recognizer = cv2.face.LBPHFaceRecognizer_create()#$cv2.createLBPHFaceRecognizer()
AttributeError: module 'cv2.cv2' has no attribute 'face_LBPHFaceRecognizer'

**Comment by mayurkadampro** [comment]
> module 'cv2.cv2' has no attribute 'face_LBPHFaceRecognizer'

I made changes in that train.py file you can check out from pull request else check out forked repo in my profile and now it's working fine.

**Comment by kitayya** [comment]
Key Error: 'Id'

**Comment by kitayya** [comment]
error is coming while tracking an image. what have to do now?
Like below error is coming
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\VENKAT\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2602, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Id'

**Comment by mayurkadampro** [comment]
> error is coming while tracking an image. what have to do now?
> Like below error is coming
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "C:\Users\VENKAT\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2602, in get_loc
> return self._engine.get_loc(key)
> File "pandas_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
> File "pandas_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
> File "pandas_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
> File "pandas_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'Id'

well, this kind of error does not appear when i am running and still if you have a problem with this then you can check out my repository i made some changes in it. and now its work very fine.

**Comment by kitayya** [comment]
I checked your repository also but still same problem is coming..
what i have to do?
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\VENKAT\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2602, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Id'

**Comment by mayurkadampro** [comment]
> I checked your repository also but still same problem is coming..
> what i have to do?
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "C:\Users\VENKAT\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2602, in get_loc
> return self._engine.get_loc(key)
> File "pandas_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
> File "pandas_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
> File "pandas_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
> File "pandas_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'Id'

then it's weird bcoz I test it then upload it. so installed all the latest version of a module then try it on python 3
pip install opencv-python
pip install pytest-shutil
pip install pandas
pip install pillow
hope it works

**Comment by nonokh** [comment]
> > I checked your repository also but still same problem is coming..
> > what i have to do?
> > Exception in Tkinter callback
> > Traceback (most recent call last):
> > File "C:\Users\VENKAT\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2602, in get_loc
> > return self._engine.get_loc(key)
> > File "pandas_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
> > File "pandas_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
> > File "pandas_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
> > File "pandas_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
> > KeyError: 'Id'
> 
> then it's weird bcoz I test it then upload it. so installed all the latest version of a module then try it on python 3
> pip install opencv-python
> pip install pytest-shutil
> pip install pandas
> pip install pillow
> hope it works

i am getting the same error
Is it necessary to run the setup.py ???

i didnt because i already have all the modules required in train.py

**Comment by mayurkadampro** [comment]
> > > I checked your repository also but still same problem is coming..
> > > what i have to do?
> > > Exception in Tkinter callback
> > > Traceback (most recent call last):
> > > File "C:\Users\VENKAT\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2602, in get_loc
> > > return self._engine.get_loc(key)
> > > File "pandas_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
> > > File "pandas_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
> > > File "pandas_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
> > > File "pandas_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
> > > KeyError: 'Id'
> > 
> > 
> > then it's weird bcoz I test it then upload it. so installed all the latest version of a module then try it on python 3
> > pip install opencv-python
> > pip install pytest-shutil
> > pip install pandas
> > pip install pillow
> > hope it works
> 
> i am getting the same error
> Is it necessary to run the setup.py ???
> 
> i didnt because i already have all the modules required in train.py

nope, it is not necessary you can directly run by running train.py file
lastly, i can say create virtual env with python 3.5 version and install all req module which is knowing you very well and try to run...

**Comment by kraverkar17** [comment]
showing unknown to every tracked image?
what to do?

**Comment by nonokh** [comment]
> > > > I checked your repository also but still same problem is coming..
> > > > what i have to do?
> > > > Exception in Tkinter callback
> > > > Traceback (most recent call last):
> > > > File "C:\Users\VENKAT\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2602, in get_loc
> > > > return self._engine.get_loc(key)
> > > > File "pandas_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
> > > > File "pandas_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
> > > > File "pandas_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
> > > > File "pandas_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
> > > > KeyError: 'Id'
> > > 
> > > 
> > > then it's weird bcoz I test it then upload it. so installed all the latest version of a module then try it on python 3
> > > pip install opencv-python
> > > pip install pytest-shutil
> > > pip install pandas
> > > pip install pillow
> > > hope it works
> > 
> > 
> > i am getting the same error
> > Is it necessary to run the setup.py ???
> > i didnt because i already have all the modules required in train.py
> 
> nope, it is not necessary you can directly run by running train.py file
> lastly, i can say create virtual env with python 3.5 version and install all req module which is knowing you very well and try to run...

WORKING!!!!!.
 okay i didnt use venv n all but yeah made a few changes. i cloned your repo but your code was getting stuck while taking images and the images wasnt being saved in the folder. i replaced  your takeimage() function by the takeimage() from the master repo(ashish). EVERYTHING IS WORKING NOW but still would suggest some changes in the project (i m not that good in python lol):

-- instead of saving a new csv file for each timestamp, it will be better to have a single csv file for each day (eg: Attendace_01_04_2019) and append the recognized faces id and names in the csv file .
so the csv file will contain a list of student who came that day. if the file is already there, ignore it else create new one 

Disadvantage of current project: creating multiple csv files every time you run.

**Comment by mayurkadampro** [comment]
> > > > > I checked your repository also but still same problem is coming..
> > > > > what i have to do?
> > > > > Exception in Tkinter callback
> > > > > Traceback (most recent call last):
> > > > > File "C:\Users\VENKAT\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2602, in get_loc
> > > > > return self._engine.get_loc(key)
> > > > > File "pandas_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
> > > > > File "pandas_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
> > > > > File "pandas_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
> > > > > File "pandas_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
> > > > > KeyError: 'Id'
> > > > 
> > > > 
> > > > then it's weird bcoz I test it then upload it. so installed all the latest version of a module then try it on python 3
> > > > pip install opencv-python
> > > > pip install pytest-shutil
> > > > pip install pandas
> > > > pip install pillow
> > > > hope it works
> > > 
> > > 
> > > i am getting the same error
> > > Is it necessary to run the setup.py ???
> > > i didnt because i already have all the modules required in train.py
> > 
> > 
> > nope, it is not necessary you can directly run by running train.py file
> > lastly, i can say create virtual env with python 3.5 version and install all req module which is knowing you very well and try to run...
> 
> WORKING!!!!!.
> okay i didnt use venv n all but yeah made a few changes. i cloned your repo but your code was getting stuck while taking images and the images wasnt being saved in the folder. i replaced your takeimage() function by the takeimage() from the master repo(ashish). EVERYTHING IS WORKING NOW but still would suggest some changes in the project (i m not that good in python lol):
> 
> -- instead of saving a new csv file for each timestamp, it will be better to have a single csv file for each day (eg: Attendace_01_04_2019) and append the recognized faces id and names in the csv file .
> so the csv file will contain a list of student who came that day. if the file is already there, ignore it else create new one
> 
> Disadvantage of current project: creating multiple csv files every time you run.

I'm glad to know finally its working and yes you can change it to same csv file all you need to store the first created csv file name and append newly created data into it...
refer the same code where all Student names store in StudentDetail.csv file

**Comment by kraverkar17** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/49135591/55350916-c1a60f00-54da-11e9-9aa6-d8aa24c3d45b.png)




in if statement of line 176 I've changed a bit because with previous statement the window was getting stuck with the error mentioned above.....and no error is their but when tracking the image it is showing unknown all the time......

**Comment by nonokh** [comment]
> ![Screenshot (1)](https://user-images.githubusercontent.com/49135591/55350916-c1a60f00-54da-11e9-9aa6-d8aa24c3d45b.png)
> 
> in if statement of line 176 I've changed a bit because with previous statement the window was getting stuck with the error mentioned above.....and no error is their but when tracking the image it is showing unknown all the time......

maybe it is not passing the if() condition you have just changed.
i am guessing something to do with the 'Id'.

did you try this forked repo?
https://github.com/mayurkadampro/Face-Recognition-Based-Attendance-System

give this a try and see if it works. it worked for me

**Comment by kraverkar17** [comment]
> > ![Screenshot (1)](https://user-images.githubusercontent.com/49135591/55350916-c1a60f00-54da-11e9-9aa6-d8aa24c3d45b.png)
> > in if statement of line 176 I've changed a bit because with previous statement the window was getting stuck with the error mentioned above.....and no error is their but when tracking the image it is showing unknown all the time......
> 
> maybe it is not passing the if() condition you have just changed.
> i am guessing something to do with the 'Id'.
> 
> did you try this forked repo?
> https://github.com/mayurkadampro/Face-Recognition-Based-Attendance-System
> 
> give this a try and see if it works. it worked for me

not working.......window is stucking and the following error is showing though I have installed all the moduls which r required

Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Users\VENKAT\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexes\base.py", line 2602, in get_loc
return self._engine.get_loc(key)
File "pandas_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
File "pandas_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
File "pandas_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
File "pandas_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Id'

**Comment by tanejasarthak** [comment]
Not Working.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/sarthak/Downloads/desktop/lib/python3.7/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "train.py", line 154, in TrainImages
    recognizer = cv2.face.LBPHFaceRecognizer_create()#$cv2.createLBPHFaceRecognizer()
AttributeError: module 'cv2.cv2' has no attribute 'face'

**Comment by mayurkadampro** [comment]
> Not Working.
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "/home/sarthak/Downloads/desktop/lib/python3.7/tkinter/**init**.py", line 1702, in **call**
> return self.func(*args)
> File "train.py", line 154, in TrainImages
> recognizer = cv2.face.LBPHFaceRecognizer_create()#$cv2.createLBPHFaceRecognizer()
> AttributeError: module 'cv2.cv2' has no attribute 'face'

replace cv2.face.LBPHFaceRecognizer_create() with cv2.createLBPHFaceRecognizer() and test it again

**Comment by nonokh** [comment]
> Not Working.
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "/home/sarthak/Downloads/desktop/lib/python3.7/tkinter/**init**.py", line 1702, in **call**
> return self.func(*args)
> File "train.py", line 154, in TrainImages
> recognizer = cv2.face.LBPHFaceRecognizer_create()#$cv2.createLBPHFaceRecognizer()
> AttributeError: module 'cv2.cv2' has no attribute 'face'

u are missing components of Opencv.
Try
sudo apt install opencv-contrib-python

then run the code again.

Also, you can try the workaround mentioned by mayurkadampro too.

**Comment by divyasri456** [comment]
not working
![image](https://user-images.githubusercontent.com/45874382/55409317-74c84400-557f-11e9-9ce4-d463578e8e10.png)

**Comment by nonokh** [comment]
> not working
> ![image](https://user-images.githubusercontent.com/45874382/55409317-74c84400-557f-11e9-9ce4-d463578e8e10.png)

Try these: 

replace cv2.createLBPHFaceRecognizer() with cv2.face.LBPHFaceRecognizer_create() on line 154

next install other components of opencv 

_sudo apt install opencv-contrib-python_

then run the code again.

**Comment by syarwani03** [comment]
> > module 'cv2.cv2' has no attribute 'face_LBPHFaceRecognizer'
> 
> I made changes in that train.py file you can check out from pull request else check out forked repo in my profile and now it's working fine.

i'm sorry,, i still facing this error. where changes u talk about? please make it clear. thank u

**Comment by shivapasupuleti** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\pc\Downloads\Face-Recognition-Based-Attendance-System-master\train.py", line 161, in TrainImages
    recognizer = cv2.face_LBPHFaceRecognizer.create()#recognizer = cv2.face.LBPHFaceRecognizer_create()#$cv2.createLBPHFaceRecognizer()
AttributeError: module 'cv2.cv2' has no attribute 'face_LBPHFaceRecognizer'

**Comment by janny-sins** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Claire\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Users\Claire\Desktop\New folder (6)\login-verification-master\run.py", line 161, in login_submit
    TrackImages(a)
  File "C:\Users\Claire\Desktop\New folder (6)\login-verification-master\run.py", line 135, in TrackImages
    aa=df.loc[df['Id'] == Id]['Name'].values
  File "C:\Users\Claire\AppData\Roaming\Python\Python36\site-packages\pandas\core\frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Claire\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'Id'

please help me with this one too.
