### ISSUE TITLE
key error:'id'

### ISSUE THREAD

**Issue by venkatsaivarun** [ashish8858/Face-Recognition-Based-Attendance-System#8]
Traceback (most recent call last):
  File "C:\Users\venka\Anaconda3\envs\opencv-env\lib\site-packages\pandas\core\indexes\base.py", line 2602, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\venka\Anaconda3\envs\opencv-env\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "train.py", line 213, in TrackImages
    aa=df.loc[df['Id'] == Id]['Name'].values
  File "C:\Users\venka\Anaconda3\envs\opencv-env\lib\site-packages\pandas\core\frame.py", line 2917, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\venka\Anaconda3\envs\opencv-env\lib\site-packages\pandas\core\indexes\base.py", line 2604, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Id'

**Comment by omprakashpateli** [comment]
kya hai kuch bhi merko kuch nai s amaj raha hai /////
jaldi bata kya daalu li error resolve ho......
kal project dikhana hai  jaldi bataaa dost

**Comment by asthaporwal** [comment]
I am having the same issue . please help me with this.

**Comment by annu0520** [comment]
I am also having the same error. Anyone can help?

**Comment by tojosecsb** [comment]
I am also having the same error. Any solution ?

**Comment by tojosecsb** [comment]
> I am also having the same error. Any solution ?

Got the solution. Just insert a header row with Id & Name as headers

**Comment by EndWrecker** [comment]
You should create Id and Name columns in the Student Details csv file
